### ISSUE TITLE
Downloading HTML file error: IndexError: list index out of range

### ISSUE THREAD

**Issue by laseryuan** [mtayseer/infoq-downloader#9]
After run this command: 

python infoq_downloader.py http://www.infoq.com/presentations/LMAX

I got the following message:
Downloading HTML file
Traceback (most recent call last):
  File "infoq_downloader.py", line 38, in <module>
    video_url = html_doc.cssselect('video > source')[0].attrib['src']
IndexError: list index out of range

**Comment by mtayseer** [comment]
InfoQ changed their streaming to use RTMPE which is not yet supported :(
